version: '3.2'

services:
  frontend: 
    container_name: php-curse-front
    build: 
      context: .
      dockerfile: .deploy/docker/frontend/Dockerfile
    volumes:
      - ./.deploy/docker/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - .:/app
    depends_on:
      - backend
    ports:
      - "8011:80"
  backend:
    container_name: php-curse-backend
    build: 
      context: .
      dockerfile: .deploy/docker/backend/Dockerfile
    volumes:
      - .:/app
